# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SAC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SAC
    pod 'GoogleMaps', '= 2.3.0'
    pod 'Alamofire'
    pod 'MBProgressHUD'
    pod 'SwiftForms'
    pod 'Charts'
    pod 'DYQRCodeDecoder'
end
